default:
  image: node:17-alpine

stages:
  - test
  - build

before_script:
  - yarn --cwd ./backend-arktio  install
  - yarn --cwd ./frontend-arktio install

backend-test:
  stage: test
  script: 
    - yarn --cwd ./backend-arktio run test

frontend-build:
  stage: build
  script: 
    - yarn --cwd ./frontend-arktio run clean
    - yarn --cwd ./frontend-arktio run build
  artifacts:
    paths:
      - frontend-arktio/public/build

backend-build:
  stage: build
  script: 
    - yarn --cwd ./backend-arktio run clean
    - yarn --cwd ./backend-arktio run build
  artifacts:
    paths:
      - backend-arktio/build