default:
  image: node:17-alpine

stages:
  - test

before_script:
  - yarn --cwd ./backend-arktio  install
  - yarn --cwd ./frontend-arktio install

backend-test:
  stage: test
  script: 
    - yarn --cwd ./backend-arktio run test

frontend-test:
  stage: test
  script: 
    - yarn --cwd ./frontend-arktio run test