before_script:
  - apt-get update -qq
  - curl -L https://npmjs.org/install.sh | sudo sh
  - npm install --global yarn
  - yarn --version

test:
  stage: test
  script: 
    - yarn --cwd ./backend-arktio run test