default:
  image: node:17-alpine

stage:
  - setup
  - test

setup:
  stage: setup
  script:
    - yarn --cwd ./backend-arktio install

test:
  stage: test
  script: 
    - yarn --cwd ./backend-arktio run test