before_script:
  - apt update -qq
  - apt install curl sudo -y
  - curl -L https://npmjs.org/install.sh | sudo sh
  - npm install --global yarn
  - yarn --version

test:
  stage: test
  script: 
    - yarn --cwd ./backend-arktio run test