before_script:
  - curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  - apt update -qq
  - apt install -y curl sudo nodejs
  - curl -L https://npmjs.org/install.sh | sudo sh
  - npm install --global yarn
  - yarn --version

test:
  stage: test
  script: 
    - yarn --cwd ./backend-arktio run test