import {Case, TypeReponse} from "../caseManager";
import {State} from "../state";

export default class CaseInformation implements Case {
    name = "Information";
    id_name = "info";
    max_number = 3;

    informations: string[] = [];

    constructor() {
        this.informations.push("Campus Vert Strasbourg est l\'Association au sein de l\'Université dédiée à la transition écologique. Si tu souhaites entrer en contact avec des personnes engagées ou participer à tes ateliers concrets n\'hésite pas à frapper à leur porte ! Je veux en savoir plus : https://www.campusvertstrasbourg.org");
        this.informations.push("Envie de t\'engager pour une mission qui a du sens ? Deviens éco-volontaire et prends part à des projets de protection de la biodiversité, d\'agroécologie ou de transition énergétique. En quelques semaines, tu auras l\'opportunité de participer à des actions concrètes au profit du bien commun. Comment devenir éco-volontaire ? Cap sur l\'écovolontariat : https://www.eco-volontaire.com/\nEcovoyageurs : https://www.ecovoyageurs.com/ecovolontariat.html");
        this.informations.push("L\'Université de Strasbourg agit en faveur du développement durable au travers d\'une cellule spécialement dédiée. C'est elle qui fournit les Eco-guides que tu reçois dans ta boîte afin de te sensibiliser aux bonnes pratiques. En savoir plus sur les actions de la Mission développement durable et resposnabilité sociétale de l'Unistra : https://www.unistra.fr/developpement-durable");
        this.informations.push("Avec le savon noir, le vinaigre blanc est la base de tout produit d'entretien à faire soi-même. Détartrant, désinfectant, répulsif… Même si tu n'es pas prêt.e à faire toi-même tes produits ménagers, connaître ses vertus (et le cadre de ses utilisations) est un premier pas pour limiter le nombre de bouteilles aux compositions nébuleuses qui chargent tes étagères !");
        this.informations.push("Plutôt lavable ou jetable ? La comparaison doit se faire sur plusieurs niveaux et surtout en prenant en compte l'Analyse du Cycle de Vie du produit (ACV), c'est-à-dire l'impact de sa fabrication, de son usage et de sa fin de vie sur l'environnement. La consommation d'eau lors de la fabrication et du lavage notamment, les matériaux utilisés (le chanvre au lieu du coton), l'empreinte carbone... A vos calculs ! Vous verrez que l'argument des lavages répétés ne tiens pas longtemps ! Sinon vous pouvez jeter un oeil à l'article écrite par Manamani (https://manamani.com/lavable-vs-jetable/)");
        this.informations.push("Qu'est-ce qui fait un produit éco-responsable ? Comme pour tout produit de consommation, il faut se reporter à sa composition et faire attention à l'origine de ses composants ou de ses ingrédients. En effet, l'éthique de fabrication, l'empreinte carbone globale du produit, l'emballage, la qualité des ingrédients ou encore la collecte des déchets recyclabes de petite taille (têtes de brosses à dents par exemple)... Tout cela entre en compte ! Bien sûr tout produit éco-responsable ne coche pas l'ensemble des critères, les contraintes de productions liées au secteur rendent parfois impossible (à l'heure actuelle) le produit parfait. Malgré tout, ces marques sont toujours à la recherche de nouvelles méthodes ou filières pour limiter l'empreinte carbone de leurs produits.");
        this.informations.push("Le lien entre véganisme et écologie n'est pas aussi évident qu'il y paraît. Les véganes luttent contre l'élevage intensif, l'exploitation et la maltraitance animale, pour cela tout produit d'origine animale est banni de leur alimentation. Cependant, il reste un pas à faire pour penser à l'empreinte carbone de son alimentation. En effet, un certain nombre de subsituts végétaux ou de légumineuses sont importés d'Asie ou d'Amérique du Sud dans des conditions de production pas toujours éthiques. Nombre de véganes se senbilisent à l'écologie justement par leur alimentation et leur engagement pour le bien-être animal qui est en l'un des nombreux combats ! https://reporterre.net/Les-veganes-sont-ils-ecolos");
        this.informations.push("Difficile de s'y retrouver entre tous les labels bio, neutres en carbone, équitables, éthiques… De nombreuses applications existent pour scanner ses aliments pour vérifier leur qualité mais il peut être utile de décortiquer les labels et leur cahier des charges. \nDescriptif des écolabels : https://www.notre-planete.info/ecologie/eco-citoyen/labels_ecologiques.php\nClassements des écolabels par fiabilité selon Greenpeace : https://www.guide-labels-alimentaires.com/#/");
        this.informations.push("Comme tout écosystème, l'écologie est un lieu d'interaction et d'interdépendance. On commence généralement à s'intéresser à l'écologie par un aspect : la protection de la biodiversité, l'alimentation saine, l'énergie renouvelable. Tous ces combats sont aussi importants les uns que les autres et font partie du même ensemble. Il en va de même dans notre alimentation, penser qu'une alimentation 100% bio mais suremballée et importée n'est pas viable, tout comme du 100% local mais avec usage de pesticides ou dans des conditions d'élevage déplorable. Tout est une question d'équilibre et de connaissance de ce que l'on consomme et de celleux qui produisent.");
        this.informations.push("Qu'est-ce que le cycle de vie d'un produit d'un point d'empreinte carbone ? Contrairerement à l'analyse marketing, on prend en compte la vie du produit de sa conception à sa destruction. L'intérêt de cette approche est de juger l'impact du produit à chaque étape afin de définir des points de vigilances ou d'amélioration en vue de limiter l'empreinte carbone par la suite en innovant ou en modifiant le processus de production, d'acheminement, de conditionnement... Il s'agit d'une approche multicritère que de plus en plus de marques écoresponsables intègrent dans leur réflexion.\nhttps://expertises.ademe.fr/economie-circulaire/consommer-autrement/passer-a-laction/dossier/lanalyse-cycle-vie/quest-lacv");
        this.informations.push("L'approche du zéro déchet se base sur les 5 R. 5 étapes de réflexion autour de sa consommation : réfuser ce dont on n'a pas besoin, réduire sa consommation au nécessaire, réutiliser ce qui peut l'être, recycler ce qui ne peut être réutiliser, redonner (composter, valoriser).\nPlus d'informations sur le zéro déchet : https://www.zerowastefrance.org/demarche-zero-waste/");
        this.informations.push("Connais-tu le défi rien de neuf organisé par Zero Waste France ? L'objectif est de limiter au maximum ses achats de produits neufs au profit d'objets de seconde main ou reconditionné. C'est l'occasion de partir à la découverte des friperies et des magasins de seconde main de Strasbourg.\nPrêt.e à relever le défi ?\nhttps://riendeneuf.org/");
        this.informations.push("Un tiers-lieu est un endroit alternatif de projet collectif mis en œuvre par des citoyens. Ils peuvent prendre différentes formes : repair cafés, fablab, coworking, ateliers culturels… Ce sont toujours des lieux d'échange et de partage, qui favorisent la créativité et le lien social. De formes juridiques et de financements variés, chacun s'organise selon l'axe qui lui est propre.\nA Strasbourg, découvre le Shadok : https://www.shadok.strasbourg.eu/\nKaleidosCOOP: http://www.kaleidos.coop/kaleidoscoop/");
        this.informations.push("Pour s'informer, s'impliquer, rencontrer des personnes sont les centres d'intérêts (et par parfois d'angoisse…) rejoignent les nôtres, rien de mieux de les associations. Tu as certainement entendu parler de certaines qui font parler d'elles par l'organisation de CleanUp Days, d'ateliers, de manifestations. Et si tu sautais le pas ?\nDécouvrir Zero Waste France : https://www.zerowastefrance.org\nDécouvrir Alternatiba : https://alternatiba.eu/\nDécouvrir Greenpeace : https://www.greenpeace.fr/");
        this.informations.push("Tu souhaites agir mais tu ne sais pas comment faire ? De nombreux leviers sont à ta portée !\nTu peux soutenir des luttes en signant des pétitions : https://secure.avaaz.org/page/fr/\nTu peux participer à des marches pour le climat : https://fridaysforfuture.org/\nC'est relayer des messages ou réagir sur les réseaux sociaux : https://instagram.com/stopeacop?igshid=YmMyMTA2M2Y=");
        this.informations.push("Tu le sais peut-être, mais en 2020 le numérique pesait pour 3 à 4 % des émissions de gaz à effet de serre u niveau mondial et cela ne cesse d'augmenter. On ne sent rend pas compte mais toutes les données dématérialisées doivent être stockées dans des centres de données qui doivent restés allumés et refroidis 24h/24, 7j/7. Cela demande une énergie phénoménale. \nQue peux-tu faire à ton échelle ? \nVider régulièrement ta boite mail et limiter l'envoi de pièces-jointes\nEnregistrer dans tes favoris, les sites que tu consultes régulièrement\nEteindre tes appareils électroniques et ta box quand tu ne les utilises pas\nUtiliser des moteurs de recherches solidaires comme Ecosia ou Lilo\nLimiter ton temps passé sur les platerformes de streaming");
        this.informations.push("Les données numériques ne sont pas stockées dans l'air mais sur d'énormes serveurs qui demandent des locaux bien réels, de l'électricité et du refroidissement. Elles ont donc un impact sur notre planète et émettent du CO2. Il peut donc parfois être utile et plus responsable d'imprimer ou de se procuper les éditions papier de travaux que l'on compte consulter régulièrement. Comme pour tout, l'équilibre est à trouver selon les besoins de chacun !");
        this.informations.push("La low-tech est souvent mise en opposition à la high-tech. On parle d'objets mais surtout de sytèmes low-tech qui reposent des caractéristiques précises : l'utilité (répondre à un besoin réel), l'accessibilité (être compréhensible, simple et abordable), l'autonomie dans l'usage, la durabilité (faible impact environnemental, peu de ressources naturelles, pérenne), la localité. \nLa technologie et le progrès technique sont souvent mis en avant comme LA solution aux enjeux écologiques. Il est pourtant clair que la tech telle qu'elle existe aujourd'hui fait plus de mal que de bien à notre environnement.\nPlus d'informations sur les démarches low-tech étudiées par l'ADEME : https://librairie.ademe.fr/dechets-economie-circulaire/5421-demarches-low-tech.html");
        this.informations.push("Nombre d'industriels et de politiques mises sur le tout électrique, notamment la voiture. En effet, si l'on se réfère strictement à la période d'usage d'une voiture électrique, elle n'émet pas de CO2 contrairement à un véhicule thermique. Cependant, il a bien fallu la fabriquer et il faudra gérer les déchets occasionnés lorsqu'elle ne roulera plus. C'est la que le bilan est plus mitigé : les batteries de ces véhicules, tout comme tous les appareils électroniques, dépendent de terres rares dont l'exploitation se fait majoritairement en Chine dans des conditions déplorables pour les ouvriers et l'environnement. Par ailleurs, on est pour le moment incapable de recycler ces matériaux qui deviendront dans quelques années des déchets supplémentaires. La solution d'aujourd'hui sera bientôt le problème de demain....");
        this.informations.push("Tu as certainement déjà croisé un.e cycliste avec la selle affublée d'un drapeau jaune estampillé \"Au boulot à vélo !\" ? Organisé par le CADR 67 depuis 2019 ce challenge se déroule tous les ans pendant un mois et invite des équipes formées au sein de services ou d'association pour accumuler le plus de kilomètres possible parcourus à vélo entre le domicile et le travail. Une initiative conviviale et ludique pour favoriser l'usage du vélo à Strasbourg, puisque nombre de participants continuent cette bonne habittude tout au long de l'année ! https://auboulotavelo.eu/");
        this.informations.push("Découvre l'Alsace à vélo ! Le réseau de pistes cyclables alsacien est particulièrement développé et permet à chacun.e de parcourir la région à hauteur de ses capacités. De nombreux itinéraires ont été dessinés suivant la Route des Vins d'Alsace, les vallées vosgiennes ou te guideront jusqu'en Allemagne. Une idée sportive et zéro carbone pour un week-end local ! https://www.alsaceavelo.fr/");   
        this.informations.push("Quel est le point commun entre le pissenlit et l'ail des ours ? Il s'agit de plantes sauvages comestibles que tu peux récolter lors de tes balades pour agrémenter un plat ou une soupe. Deux règles d'or des cueilleurs de plantes sauvages : ne ramasse rien que tu ne reconnaisse de manière certaine et assure-toi de ne récolter que quelques spécimens et seulement si tu es dans une zone de prolifération de l'espèce. Si tu souhaites te former, il existe des ateliers ou des balades botaniques.");
        this.informations.push("Plusieurs fois dans l'année la LPO organise un weekend de comptage national des oiseaux de jardins afin de récolter des données qui seront étudiées par des ornithologues. C'est l'occasion pour toi d'apprendre à différencier le pinson des arbres du verdier l'Europe tout en profitant de la nature qui t'entoure même en ville ! Pour cela, installe-toi au moins une heure et compte le nombre de d'oiseaux de chaque espèce que tu reconnais et renseigne tes observations sur https://www.oiseauxdesjardins.fr/ ou https://www.faune-alsace.org/. Munis-toi d'un guide ornithologique ou télécharge une application de reconnaissance des oiseaux qui n'auront bientôt plus de secrets pour toi !");
        this.informations.push("As-tu déjà remarqué que tu te sens plus serein.e en forêt ? Le bruissement du vent à travers les feuilles, le babillement des oiseaux, le grincement freutré de tes pas sur l'humus. Certain.e.s vont jusqu'à enlacer un arbre avec lequel iels se sentent en connexion. Qu'importe ta pratique, les bienfaits de la sylvothérapie sont nombreux alors ne te prive pas d'arpenter les forêts vosgiennes quand tu le peux !");
        this.informations.push("As-tu entendu parlé du Stück ? Il s'agit de la monnaie locale en usage dans le Bas-Rhin. Cette monnaie est en circulation sur un marché local et peut-être échangée entre les adhérents de l'association qu'il s'agissent de professionnels ou de particuliers. L'intérêt est de valoriser les artisans et producteurs locaux. Pour adhérer, il te suffit d'inscrire sur le site ! Ne t'inquiète pas des conversions : 1 stück = 1 euro ! https://www.lestuck.eu/");
        this.informations.push("Beaucoup d'entreprises et d'Etats intègrent dans leur stratégie écologique la notion de \"neutralité carbone\". Il faut bien faire attention à ce terme puisqu'il ne s'agit pas de ne pas émettre de carbone, toute production rendrait l'objectif impossible, mais de compenser les émissions afin d'atteindre un équilibre. Pour cela, il existe un marché de crédits carbone qui servent à financer des actions de plantations d'arbres ou gestion de projets écologiques, souvent à l'autre bout du monde. Le problème de ce système est d'une part que le coût de crédit est loin d'être désincitatif (1T de CO2 coûte entre 5 et 50€ (2021)), d'autre part tant qu'elle pourra se permettre de compenser financièrement ses émissions, une organisation n'aura pas intérêt à limiter son impact alors que c'est bien l'enjeu. Le dernier rapport du GIEC l'affirme par ailleurs, nous avons jusqu'à 2025 pour inverser la tendance et réduire nos émissions de GES.");
        this.informations.push("Limiter son empreinte écologique s'inscrit aussi dans son habitation et la vie en communauté. T'es-tu déjà renseigné sur la mise à disposition d'un compost dans ton quartier ou bien sur l'existence de bâtiments passifs (qui consomment peu d'énergie) ? Tu peux te renseigner sur ces éco-quartiers à Strasbourg, les initiatives ne manquent pas ! https://www.ecoquartier-strasbourg.fr/");
        this.informations.push("Camille Etienne et Solal Moisan sont deux artistes activistes pour le climat. En 2020, ils lancent un duo avec la vidéo Réveillons-nous ! (https://www.youtube.com/watch?v=1Mw5ADaHyFo) Leur objectif : sensibiliser à l'urgence climatique et pousser à l'action grâce à l'art et la fiction. Parce que pour créer de nouveaux possibles, il faut d'abord pouvoir l'imaginer !");
    }

    play(state: State, playerID: string, choices: number[]) : State {
        return state;
    }

    getRandomInformation() : string {
        return this.informations[Math.floor(Math.random() * this.informations.length)];
    }

    prepare(state: State, playerID: string, step: number) : TypeReponse {
        return { titre: "Le savais-tu ?", messages: [ this.getRandomInformation() ] };
    }

    next(state: State, playerID: string, step: number, choice: number) : { end: boolean, step: number } {
        return { end: true, step: -1 };
    }
}